### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by WaitRainbow** [WaitRainbow/MybatisTest#2]
飞行棋

**Comment by solidjerryc** [comment]
报告监考官，发现有人作弊

**Comment by solidjerryc** [comment]
报告监考官，发现有人作弊

**Comment by solidjerryc** [comment]
报告监考官，发现有人作弊

**Comment by solidjerryc** [comment]
报告监考官，发现有人作弊

**Comment by solidjerryc** [comment]
报告监考官，发现有人作弊

**Comment by solidjerryc** [comment]
报告监考官，发现有人作弊

**Comment by solidjerryc** [comment]
报告监考官，发现有人作弊

**Comment by solidjerryc** [comment]
报告监考官，发现有人作弊

**Comment by solidjerryc** [comment]
报告监考官，发现有人作弊

**Comment by solidjerryc** [comment]
报告监考官，发现有人作弊

**Comment by WaitRainbow** [comment]
题目是4人打牌，每个人抽13张牌，每个人能每一轮出一张，比花色和数字，（黑桃>红桃>梅花>方片），最大的玩家可以将四张牌都收入积分库，手牌都出完之后，求最高积分

**Comment by solidjerryc** [comment]
这是个概率问题吧

**Comment by solidjerryc** [comment]
求最大期望

**Comment by solidjerryc** [comment]
推不出公式的话用蒙特卡罗模拟试试

**Comment by solidjerryc** [comment]
我觉得他可能是要考察你能不能把扑克牌实现吧。定义Poker类，然后继承comparable接口实现花色比较大小功能，然后再初始化发牌，进入游戏。游戏策略也有很多种，比如就随机发牌，这种最简单。或者是按照一定策略，先出小牌，然后下一个比这个人大之类的策略。最后使用这种策略用蒙特卡洛跑个几百万次，看看最高积分是多少

**Comment by WaitRainbow** [comment]
对，可以多做几个出牌策略

**Comment by solidjerryc** [comment]
所以你就先完成随机出牌，这个最简单。然后跑一百万次看结果

**Comment by WaitRainbow** [comment]
帮我想个动态的策略，比如连赢三轮就出最小，连输三轮就出最大，这样的动态策略

**Comment by solidjerryc** [comment]
我想到的是田忌赛马，如果对方出得是小牌，那我就输给他，如果是大牌，那就出个更大的。比如定8为中间值，小于8就故意输，出最小的牌，大于8 就想办法出最大的
